INSERT INTO patrons (first_name, last_name, address)
VALUES
    ('Hailey', 'Thomas', '408 Cirtus Drive'),
    ('Hero', 'Higashi', '1593 Forest Avenue'),
    ('Wilfredo', 'Mayer', '43 Amethyst Drive'),
    ('Angelica', 'Prescott', '2489 Heavner Court'),
    ('Bernetta', 'Kennard', '3078 Lunetta Street'),
    ('Myrto', 'Gaspari', '2927 Findley Avenue'),
    ('Farvald', 'Hayward', '2210 Old House Drive'),
    ('Charlie', 'Arrighetti', '3128 Ritter Avenue'),
    ('Catherine', 'Myles', '3005 Goldie Lane'),
    ('Stefan', 'Yamada', '374 Moonlight Drive'),
    ('Annabella', 'Lewis', '4423 John Avenue'),
    ('Prema', 'Averill', '1010 Whitetail Lane'),
    ('Donna', 'Lark', '123 Rainbow Ave'),
    ('Norma', 'Hartman', '2722 Ashford Drive'),
    ('Brenda', 'Frick', '2218 Broad Street'),
    ('Ronald', 'Grant', '2480 Stonecoal Road'),
    ('Ricky', 'Matz', '4493 Reynolds Alley'),
    ('Sheila', 'Fellows', '1340 Cityview Drive'),
    ('William', 'Evans', '626 Beeghley Street'),
    ('Grace', 'Gillard', '4124 Winding Way'),
    ('Charles', 'Augustine', '1219 Bolman Court'),
    ('Glenda', 'Minnick', '366 Jessie Street'),
    ('Linda', 'Smith', '543 Eden Drive'),
    ('Ronnie', 'Towler', '2135 Masonic Hill Road'),
    ('Melanie', 'Stout', '3162 Burnside Avenue');